spring.application.name=demo


# Essential broker address
bootstrap.servers=localhost:9092

# Serialization classes for keys and values
key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=org.apache.kafka.common.serialization.StringSerializer

## Reliability and acknowledgement settings
#acks=all
#retries=3
